# 開発・ビルド用コンテナ
# vscode Dec Containerを使用

FROM debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    ninja-build \
    pkg-config \
    gdb \
    git \
    libv4l-dev \
    v4l-utils \
    libyaml-cpp-dev \
    libasio-dev \
    libturbojpeg-dev \
    vim \
    bash \
    wget \
    unzip \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/4.10.0.zip && \
    wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.10.0.zip && \
    unzip opencv.zip && \
    unzip opencv_contrib.zip && \
    mkdir -p opencv-4.10.0/build && \
    cd opencv-4.10.0/build && \
    cmake -G Ninja \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.10.0/modules \
    -D WITH_V4L=ON \
    -D WITH_LIBV4L=ON \
    -D WITH_QT=OFF \
    -D WITH_GTK=OFF \
    -D BUILD_TESTS=OFF \
    -D BUILD_PERF_TESTS=OFF \
    -D BUILD_EXAMPLES=OFF \
    -D OPENCV_GENERATE_PKGCONFIG=ON \
    .. && \
    ninja && \
    ninja install && \
    ldconfig && \
    cd /tmp && \
    rm -rf opencv.zip opencv_contrib.zip opencv-4.10.0 opencv_contrib-4.10.0
WORKDIR /app

RUN echo "root:password" | chpasswd

EXPOSE 50001
EXPOSE 50002

CMD ["/bin/bash"]
